import Link from "next/link";
import { getRentPilotUser } from "./auth";

export default async function Home() {
  const user = await getRentPilotUser();
  const entry = user ? "/dashboard" : "/signup";
  const landlordEntry = user ? "/dashboard?role=landlord" : "/signup?role=landlord";
  const tenantEntry = user ? "/dashboard?role=tenant" : "/login?role=tenant";
  return <main className="landing">
    <nav className="nav shell"><Link href="/" className="brand"><span>R</span>RentPilot</Link><div className="navlinks"><Link href="/marketplace">Marketplace</Link><a href="#how">How it works</a><a href="#features">Features</a><a href="#pricing">Pricing</a></div><Link className="button button-small" href={entry}>{user ? "Open dashboard" : "Get started free"}</Link></nav>
    <section className="hero shell"><div className="eyebrow"><i />Built for landlords and tenants</div><h1>Rent, managed<br/><em>with confidence.</em></h1><p>Replace scattered chats and spreadsheets with one clear place for properties, rent records, receipts and reminders.</p><div className="hero-actions role-actions"><Link className="button" href={landlordEntry}>Continue as landlord <b>→</b></Link><Link className="button tenant-button" href={tenantEntry}>Continue as tenant <b>→</b></Link></div><a className="text-link hero-learn" href="#how">See how it works ↓</a><div className="trust"><span>✓ No credit card to start</span><span>✓ Tenants use it free</span><span>✓ Secure records</span></div></section>
    <section className="product-showcase shell" aria-label="RentPilot dashboard preview"><div className="mock-sidebar"><div className="brand light"><span>R</span>RentPilot</div><b>Overview</b><span>Properties</span><span>Tenancies</span><span>Rent records</span><span>Reminders</span></div><div className="mock-main"><div className="mock-head"><div><small>AUGUST 2026</small><h2>Good morning, Michael.</h2></div><button>+ Add property</button></div><div className="stats"><div><small>Rent confirmed</small><strong>₦1,240,000</strong><span className="up">↑ 8.4%</span></div><div><small>Occupancy</small><strong>92%</strong><span>11 of 12 units</span></div><div><small>Awaiting review</small><strong>₦180,000</strong><span className="warn">2 receipts</span></div></div><div className="rent-list"><div className="list-head"><b>Recent rent activity</b><span>View all</span></div>{[["AO","Ada Okafor","Lekki Court · Unit 4B","₦180,000","Confirmed"],["CT","Chidi Thomas","Yaba Place · Flat 2","₦120,000","Review"],["BN","Blessing Nwosu","Ikeja Gardens · 3A","₦150,000","Overdue"]].map(x=><div className="rent-row" key={x[1]}><i>{x[0]}</i><div><b>{x[1]}</b><small>{x[2]}</small></div><strong>{x[3]}</strong><span className={x[4].toLowerCase()}>{x[4]}</span></div>)}</div></div></section>
    <section className="property-gallery shell"><div><small>HOMES, CLEARLY MANAGED</small><h2>Every property has a place.</h2></div><div>{[1,2,3,4].map(n=><img key={n} src={`/property-${n}.png`} alt={`RentPilot managed property ${n}`}/>)}</div></section>
    <section id="features" className="feature-section shell"><div className="section-intro"><small>LESS ADMIN. MORE CERTAINTY.</small><h2>One shared truth for every rent.</h2></div><div className="feature-grid">{[["01","Upload & confirm","Tenants upload payment receipts; landlords review and confirm them."],["02","Shared records","Landlords, tenants and teams see the information meant for them."],["03","Gentle reminders","Send ready-made rent reminders by email or WhatsApp."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="how" className="steps shell"><small>HOW IT WORKS</small><h2>From payment to confirmation.</h2><div><article><b>1</b><h3>Tenant records payment</h3><p>Add the amount, period and payment date.</p></article><article><b>2</b><h3>Receipt is uploaded</h3><p>A secure copy stays attached to the rent record.</p></article><article><b>3</b><h3>Landlord confirms</h3><p>Both sides now share a trusted, confirmed record.</p></article></div></section>
    <section id="pricing" className="pricing shell"><div><small>SIMPLE EARLY-ACCESS PRICING</small><h2>Tenants are always free.</h2><p>Track properties, tenants, leases and rent records in one place. Online payment integrations are planned for a later release.</p></div><article><span>LANDLORD PRO</span><h3>₦5,000<small>/ month</small></h3><ul><li>Up to 10 properties</li><li>Unlimited tenants and receipts</li><li>Team access and reminders</li></ul><Link className="button" href={entry}>Start free trial →</Link></article></section>
    <section className="cta shell"><div><small>READY WHEN YOU ARE</small><h2>Make rent feel simple again.</h2><p>Join RentPilot early access and help shape a better experience for renters and property owners.</p></div><Link className="button cream" href={entry}>Create your workspace →</Link></section>
    <footer className="shell"><div className="brand"><span>R</span>RentPilot</div><p>Clear records. Better relationships.</p><small>© 2026 RentPilot</small></footer>
  </main>;
}
